BeginTestCase "GitHub: vérifier peut accéder à VS Code online quand on est authentifié"
// Premier pas: tout quitter
"01_steps/system".j_initialise_le_systeme

--
"01_steps/github".je_m_authentifie_a_github
"01_steps/github".je_vais_sur_le_repo_de_test
"01_steps/github".je_tente_d_ouvrir_vs_code_online

--
"01_steps/vscode_online/etat_app".je_verifie_que_vscode_online_s_est_ouvert
"01_steps/vscode_online/manipuler_fichiers".je_cree_un_nouveau_fichier_dans_vscode
"01_steps/vscode_online/manipuler_fichiers".j_ecris_dans_le_nouveau_fichier_dans_vscode
"01_steps/vscode_online/manipuler_fichiers".je_supprimme_le_nouveau_fichier_dans_vscode

EndTestCase "GitHub: vérifier peut accéder à VS Code online quand on est authentifié"