BeginTestCase "GitHub: vérifier peut accéder à VS Code online quand on est authentifié"
// Les fonctions peuvent etre des fichiers (permet de glisser/déposer dans le script)
"01_steps/github".je_m_authentifie_a_github
"01_steps/github".je_vais_sur_le_repo_de_test
"01_steps/github".je_tente_d_ouvrir_vs_code_online

"01_steps/vscode_online/etat_app".je_verifie_que_vscode_online_s_est_ouvert

// Ou des fichiers peuvent cotnenir plusieurs fonctions
"01_steps/vscode_online/manipuler_fichiers".je_cree_un_nouveau_fichier_dans_vscode
"01_steps/vscode_online/manipuler_fichiers".j_ecris_dans_le_nouveau_fichier_dans_vscode
"01_steps/vscode_online/manipuler_fichiers".je_supprimme_le_nouveau_fichier_dans_vscode

"01_steps/system".je_quitte_les_applications
EndTestCase "GitHub: vérifier peut accéder à VS Code online quand on est authentifié"