"03_framework/steps/github".je_vais_sur_le_repo_de_test

"03_framework/steps/github".je_tente_d_ouvrir_vs_code_online

Log "Vérifier que VS Code n'est pas ouvert ..."
waitfor 10, text:"github.com/lucienbill/obsidian-daily-notes", SearchRectangle: [0,0,RemoteScreenSize().x, 93]
waitfor 10, text:"lucienbill/obsidian-daily-notes", SearchRectangle: [0,93,RemoteScreenSize().x, 300]

LogSuccess "Vérifier que VS Code n'est pas ouvert : OK"

log "Quitter le navigateur ..."
typeText altKey, f4
WaitForNotFound 15, "01_monolithe/chrome_icone_chargement"
logSuccess "Quitter le navigateur : OK"
