BeginTestCase "Create a new part in Nx"
launch_NX
create_part_x_in_folder_y "tmp_part", "C:\CAD"
orientView "Top"
createNewSketch
drawARectangle
extrudeRectangle
measureExtrusion
cutCircleIntoThePiece
updateDiameterOfCircle
saveThePart
EndTestCase "Create a new part in Nx"

--------------------------------------------
BeginTestCase "Close the part, open it again"
closeThePart
openPart_x_in_folder_y "tmp_part", "C:\CAD"
closeThePart
EndTestCase "Close the part, open it again"

quit_NX