BeginTestCase "GitHub: vérifier peut accéder à VS Code online quand on est authentifié"
// Les fonctions peuvent etre des fichiers (permet de glisser/déposer dans le script)
Run "01-steps/github/je_m_authentifie_a_github"
Run "01-steps/github/je_vais_sur_le_repo_de_test"
Run "01-steps/github/je_tente_d_ouvrir_vs_code_online"

Run "01-steps/vscode_online/etat_app/je_verifie_que_vscode_online_s_est_ouvert"

// Ou des fichiers peuvent cotnenir plusieurs fonctions
"01-steps/vscode_online/manipuler_fichiers".je_cree_un_nouveau_fichier_dans_vscode
"01-steps/vscode_online/manipuler_fichiers".j_ecris_dans_le_nouveau_fichier_dans_vscode
"01-steps/vscode_online/manipuler_fichiers".je_supprimme_le_nouveau_fichier_dans_vscode

"01-steps/system".je_quitte_les_applications
EndTestCase "GitHub: vérifier peut accéder à VS Code online quand on est authentifié"