logfct
waitfor 30, text: "github.dev/lucienbill/obsidian-daily-notes", SearchRectangle:empty
wait 4 // FIXME : on peut faire plus subtil
waitfor 30, text: "The extension 'GitHub Repositories' wants to sign in using GitHub."

Log "Autoriser le login et attendre le chargement du repo ..."
click "Allow"
wait 1
click "lucienbill-ks"
wait 4
waitfor 30, text: "What's that thing for (description)?"
logfct